version: '3.9'
services:
    app:
      build: .
      image: docker-demo:v1
      networks: 
      - my-network
      ports:
        - "8080:8080"
    
    mongodb:
      image: "mongodb/mongodb-community-server:latest"
      networks:
      - my-network
      volumes:
        - mongo-data:/data/db
networks:
  my-network:
      driver: bridge
    
volumes:
  mongo-data:
    driver: local





      


    
      
